name: 'Setup Java'
description: 'Setup Java'

inputs:
  java-version:
    description: "Java version"
    default: "17"

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: adopt
