name: Check Status
on: push
jobs:
  assemble_debug:
    name: Assemble Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run gradlew assembleDebug
        uses: ./.github/actions/assemble-debug
