name: Check Status
on: push
jobs:
  assemble_debug:
    name: Assemble Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run gradlew assembleDebug
        uses: ./.github/actions/assemble-debug
  upload_debug:
    name: Upload Debug
    needs: assemble_debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ./app/build/outputs/apk/debug/app-debug.apk
  send_artifact_link_to_slack:
    name: Send Artifact Link to Slack
    needs: upload_debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Send Slack Message
        uses: ./.github/actions/send-artifact-link-to-slack
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          artifact-name: app-debug
          artifact-link-url: ${{ steps.upload_debug.outputs.artifact-url }}
