name: Check Status
on: push
jobs:
  assemble_debug:
    name: Assemble Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run gradlew assembleDebug
        uses: ./.github/actions/assemble-debug
  send_artifact_link_to_slack:
    name: Send Artifact Link to Slack
    needs: assemble_debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Send Slack Message
        uses: ./.github/actions/send-artifact-link-to-slack
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
