name: Check Status
on: push
jobs:
  assemble_debug_and_upload:
    name: Assemble Debug and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run gradlew assembleDebug
        uses: ./.github/actions/assemble-debug
      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ./app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
      - name: Send Slack Message
        uses: ./.github/actions/send-artifact-link-to-slack
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          artifact-name: app-debug
          artifact-link-url: ${{ steps.upload_artifact.outputs.artifact_url }}
